
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 14 10:38:37 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 3;
  public static final int PUNTO = 2;
  public static final int LETRA = 4;
  public static final int EOF = 0;
  public static final int SEPARADOR = 7;
  public static final int PARIZQ = 5;
  public static final int WRITE = 9;
  public static final int error = 1;
  public static final int PARDER = 6;
  public static final int COMILLA = 8;
}

